import { Router, type IRouter } from "express";
import healthRouter from "./health";
import contactsRouter from "./contacts";
import companiesRouter from "./companies";
import dealsRouter from "./deals";
import activitiesRouter from "./activities";
import signalsRouter from "./signals";
import segmentsRouter from "./segments";
import callsRouter from "./calls";
import scriptsRouter from "./scripts";
import notificationsRouter from "./notifications";
import dashboardRouter from "./dashboard";
import analyticsRouter from "./analytics";
import aiRouter from "./ai";
import aiExtraRouter from "./ai-extra";
import usersRouter from "./users";
import propertiesRouter from "./properties";
import listsRouter from "./lists";
import viewsRouter from "./views";
import dashboardsRouter from "./dashboards";
import automationsRouter from "./automations";
import campaignsRouter from "./campaigns";
import agentsRouter from "./agents";
import trackingRouter from "./tracking";
import seedExtraRouter from "./seed-extra";
import businessCardsRouter from "./business-cards";
import playbooksRouter from "./playbooks";
import activityCaptureRouter from "./activity-capture";
import attributionRouter from "./attribution";
import healthScoresRouter from "./health-scores";
import redactionRouter from "./redaction";
import dedupRouter from "./dedup";
import marketingExtrasRouter from "./marketing-extras";
import powerDialerRouter from "./power-dialer";
import leadEnrichRouter from "./lead-enrich";
import investorsRouter from "./investors";
import napkinRouter from "./napkin";
import prospectsRouter from "./prospects";
import enrichmentRouter from "./enrichment";
import enginesRouter from "./engines";
import briefingRouter from "./briefing";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/contacts", contactsRouter);
router.use("/companies", companiesRouter);
router.use("/deals", dealsRouter);
router.use("/activities", activitiesRouter);
router.use("/signals", signalsRouter);
router.use("/segments", segmentsRouter);
router.use("/calls", callsRouter);
router.use("/scripts", scriptsRouter);
router.use("/notifications", notificationsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/analytics", analyticsRouter);
router.use("/ai", aiRouter);
router.use("/ai", aiExtraRouter);
router.use("/users", usersRouter);
router.use("/properties", propertiesRouter);
router.use("/lists", listsRouter);
router.use("/views", viewsRouter);
router.use("/dashboards", dashboardsRouter);
router.use("/automations", automationsRouter);
router.use("/campaigns", campaignsRouter);
router.use("/agents", agentsRouter);
router.use("/tracking", trackingRouter);
router.use("/admin", seedExtraRouter);
router.use("/business-cards", businessCardsRouter);
router.use("/playbooks", playbooksRouter);
router.use("/activity-capture", activityCaptureRouter);
router.use("/attribution", attributionRouter);
router.use("/health-scores", healthScoresRouter);
router.use("/redaction", redactionRouter);
router.use("/dedup", dedupRouter);
router.use("/marketing", marketingExtrasRouter);
router.use("/power-dialer", powerDialerRouter);
router.use("/lead-enrich", leadEnrichRouter);
router.use("/investors", investorsRouter);
router.use("/napkin", napkinRouter);
router.use("/prospects", prospectsRouter);
router.use("/enrichment", enrichmentRouter);
router.use("/engines", enginesRouter);
router.use("/briefing", briefingRouter);

export default router;
