// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/qpulse/QPulseBrandPreview.tsx": () => import("../components/mockups/qpulse/QPulseBrandPreview.tsx"),
  "./components/mockups/crm-redesign/CRM.tsx": () => import("../components/mockups/crm-redesign/CRM.tsx"),
  "./components/mockups/crm-redesign/CallInbox.tsx": () => import("../components/mockups/crm-redesign/CallInbox.tsx"),
  "./components/mockups/crm-redesign/Company.tsx": () => import("../components/mockups/crm-redesign/Company.tsx"),
  "./components/mockups/crm-redesign/Home.tsx": () => import("../components/mockups/crm-redesign/Home.tsx"),
  "./components/mockups/crm-redesign/Navigation.tsx": () => import("../components/mockups/crm-redesign/Navigation.tsx"),
  "./components/mockups/crm-redesign/NavigationV2.tsx": () => import("../components/mockups/crm-redesign/NavigationV2.tsx"),
  "./components/mockups/crm-redesign/PersonDrawer.tsx": () => import("../components/mockups/crm-redesign/PersonDrawer.tsx"),
  "./components/mockups/crm-redesign/SmartFlow.tsx": () => import("../components/mockups/crm-redesign/SmartFlow.tsx"),
  "./components/mockups/crm-redesign/Studio.tsx": () => import("../components/mockups/crm-redesign/Studio.tsx"),
  "./components/mockups/sales-rep-home/Cockpit.tsx": () => import("../components/mockups/sales-rep-home/Cockpit.tsx"),
  "./components/mockups/sales-rep-home/DailyBriefing.tsx": () => import("../components/mockups/sales-rep-home/DailyBriefing.tsx"),
  "./components/mockups/sales-rep-home/FeedRail.tsx": () => import("../components/mockups/sales-rep-home/FeedRail.tsx"),
  "./components/mockups/sales-rep-home/PerformanceTrends.tsx": () => import("../components/mockups/sales-rep-home/PerformanceTrends.tsx"),
  "./components/mockups/sales-rep-home/SplitView.tsx": () => import("../components/mockups/sales-rep-home/SplitView.tsx"),
  "./components/mockups/sales-rep-home/TodoAlerts.tsx": () => import("../components/mockups/sales-rep-home/TodoAlerts.tsx")
};
