// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sales-rep-home/DailyBriefing.tsx": () => import("../components/mockups/sales-rep-home/DailyBriefing.tsx"),
  "./components/mockups/sales-rep-home/PerformanceTrends.tsx": () => import("../components/mockups/sales-rep-home/PerformanceTrends.tsx"),
  "./components/mockups/sales-rep-home/TodoAlerts.tsx": () => import("../components/mockups/sales-rep-home/TodoAlerts.tsx")
};
